import {
  createPublicationOrderWithBalance,
  findPublicationChannel,
  findPublicationChannelForUser,
  findPublicationOrderByIdempotency,
  findPublicationOrderWithChannel,
  listPublicationChannels,
  listPublicationChannelsPage,
  listPublicationOrders,
  listPublicationOrdersPage,
  recordPublicationProviderSnapshot,
  updatePublicationOrder,
  upsertProviderPublicationChannels,
  upsertPublicationChannel,
} from "@geo/db";

export const publicationRepository = {
  findByIdempotency: findPublicationOrderByIdempotency,
  channels: listPublicationChannels,
  channelPage: listPublicationChannelsPage,
  upsertChannel: upsertPublicationChannel,
  upsertProviderChannels: upsertProviderPublicationChannels,
  findChannel: findPublicationChannel,
  findChannelForUser: findPublicationChannelForUser,
  orders: listPublicationOrders,
  orderPage: listPublicationOrdersPage,
  createOrder: createPublicationOrderWithBalance,
  updateOrder: updatePublicationOrder,
  recordProviderSnapshot: recordPublicationProviderSnapshot,
  findOrder: findPublicationOrderWithChannel,
};
