import {
  beginPublicationAction,
  dispatchPublicationAction,
  settlePublicationAction,
  resolvePublicationAction,
  createPublicationOrderWithBalance,
  findPublicationChannel,
  findPublicationChannelForUser,
  findPublicationOrderByIdempotency,
  findPublicationSubmissionReplay,
  findTenantPublicationManuscript,
  findAdminPublicationManuscript,
  findPublicationOrderWithChannel,
  listPublicationChannels,
  listPublicationChannelsPage,
  listPublicationOrders,
  listPublicationOrdersPage,
  listAdminPublicationOrdersPage,
  findAdminPublicationOrder,
  findAdminPublicationChannel,
  recordPublicationProviderSnapshot,
  updatePublicationOrder,
  upsertProviderPublicationChannels,
  upsertPublicationChannel,
  updatePublicationChannel,
} from "@geo/db";

export const publicationRepository = {
  beginAction: beginPublicationAction,
  dispatchAction: dispatchPublicationAction,
  settleAction: settlePublicationAction,
  resolveAction: resolvePublicationAction,
  findByIdempotency: findPublicationOrderByIdempotency,
  findSubmissionReplay: findPublicationSubmissionReplay,
  manuscript: findTenantPublicationManuscript,
  adminManuscript: findAdminPublicationManuscript,
  channels: listPublicationChannels,
  channelPage: listPublicationChannelsPage,
  upsertChannel: upsertPublicationChannel,
  updateChannel: updatePublicationChannel,
  adminChannel: findAdminPublicationChannel,
  upsertProviderChannels: upsertProviderPublicationChannels,
  findChannel: findPublicationChannel,
  findChannelForUser: findPublicationChannelForUser,
  orders: listPublicationOrders,
  orderPage: listPublicationOrdersPage,
  adminOrderPage: listAdminPublicationOrdersPage,
  adminOrder: findAdminPublicationOrder,
  createOrder: createPublicationOrderWithBalance,
  updateOrder: updatePublicationOrder,
  recordProviderSnapshot: recordPublicationProviderSnapshot,
  findOrder: findPublicationOrderWithChannel,
};
